README.md
Replace the old **_Jupiter007-43_** namespace by **_ubuntu_** into the README.
=> Update README scripts path

oxt/description.xml, oxt/registration/license.txt
- Add icon license
- Update repository link
=> Oxt information update

build.sh, generate-links.sh
Just create a generate-links.sh script which copy the **links.txt** file from **/src** to **/build/png** and **/build/svg**.
=> Create a generate-links.sh script

build/png/links.txt, build/svg/links.txt, src/links.txt
=> Fix nonexistent icons links into links.txt

yaru-theme.update.xml
Add update information of the 2020-09-20 snapshot on Libreoffice ext site.
=> 2020-09-20 snapshot

README.md
Add information of the LO ext site to the README.md
=> Update README.md with Lo ext site

oxt/description.xml
Update OXT version to prepare 2020-09-28 snapshot.
=> Prepare 2020-09-28 snapshot

yaru-theme.update.xml
Update yaru-theme.update.xml for 2020-09-28 snapshot.
=> Update yaru-theme.update.xml for 2020-09-28 snapshot

.github/workflows/check-links.yml, check-links.sh
- Create a check-links.sh file
- Add a check-links Github Action
Closes #116
=> Links check

check-links.sh, src/links.txt
=> Fix links.txt

build/png/links.txt, build/svg/links.txt
Regenerate links as part of #118
=> Regenerate links

check-links.sh
Add checks for build/***/links.txt files.
=> Check build/***/links.txt files

oxt/description.xml
Update OXT version to prepare 2020-10-04 snapshot.
=> Update OXT version

yaru-theme.update.xml
Update yaru-theme.update.xml for 2020-10-04 snapshot.
=> Update yaru-theme.update.xml for 2020-10-04 snapshot

oxt/description.xml
Update OXT version to prepare 2020-10-11 snapshot.
=> Update OXT version for 2020-10-11 snapshot

yaru-theme.update.xml
Update yaru-theme.update.xml for 2020-10-11 snapshot.
=> Update yaru-theme.update.xml for 2020-10-11 snapshot

oxt/description.xml
Update OXT version to prepare 2020-10-18 snapshot.
=> Prepare 2020-10-18 snapshot

build.sh
`build.sh -w` also watch links.txt
=> build.sh also watch links.txt

oxt/description.xml
Update OXT version (2020-11-29 snapshot)
=> Update OXT version (2020-11-29 snapshot)

oxt/description.xml, yaru-theme.update.xml
Update yaru-theme.update.xml for 2020 11 29 snapshot
=> Update yaru-theme.update.xml for 2020 11 29 snapshot

README.md
=> Add snap warning into README

build.sh
@ricotz I also added a `--zip` flag to only generate ZIPs.
Closes #285
=> Better build script sepd checks

build/bark/png/links.txt, build/bark/svg/links.txt, build/blue/png/links.txt, build/blue/svg/links.txt, build/default/png/links.txt, build/default/svg/links.txt, build/magenta/png/links.txt, build/magenta/svg/links.txt, build/mate/png/links.txt, build/mate/svg/links.txt, build/olive/png/links.txt, build/olive/svg/links.txt, build/prussiangreen/png/links.txt, build/prussiangreen/svg/links.txt, build/purple/png/links.txt, build/purple/svg/links.txt, build/red/png/links.txt, build/red/svg/links.txt, build/sage/png/links.txt, build/sage/svg/links.txt, build/viridian/png/links.txt, build/viridian/svg/links.txt, src/links.txt
Related to https://github.com/rizmut/libreoffice-style-colibre/pull/53
=> Improve navigate by
